app:
  group: whokan
  fqdn: whokan.nickknows.net
backend:
  image: docker.io/ncging/whokan-backend:2025-06-10.05.08
frontend:
  image: docker.io/ncging/whokan-frontend:2025-06-08.05.31
db:
  name: whogres
  instances: 3
  size: 10Gi
  secretPath: whokan
  app:
    name: whokan-db
    owner: whokan
  superuser:
    userKey: pgsuper
    passwordKey: pgsupass
  appuser:
    userKey: pguser
    passwordKey: pguserpass