app:
  group: whokan
  fqdn: whokan.nickknows.net
  secretKeyPath: whokan
  secretKeyProperty: secret_key_value
backend:
  image: docker.io/ncging/whokan-backend:2026-03-01.16.45
frontend:
  image: docker.io/ncging/whokan-frontend:2026-03-01.16.43
redis:
  image: redis:7-alpine
db:
  name: whogres
  instances: 1
  size: 10Gi
  secretPath: whokan
  app:
    name: whokan-db
    owner: whokan
  superuser:
    userKey: pgsuper
    passwordKey: pgsupass
  appuser:
    userKey: pguser
    passwordKey: pguserpass