apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whokan-secret-key-eso
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: whokan-secret-key
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.app.secretKeyPath }}
        property: {{ .Values.app.secretKeyProperty }}
