apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    group: {{ .Values.app.group }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "your-secret-key-value"
        - name: POSTGRES_HOST
          value: "whogres-rw"