apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whokan-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: whokan
    group: {{ .Values.app.group }}
  annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.app.fqdn }}
      secretName: whokan-tls
  rules:
    - host: {{ .Values.app.fqdn }}
      http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        - path: /docs
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        - path: /redoc
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        - path: /openapi.json
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080