apiVersion: v1
kind: Service
metadata:
  name: whokan-redis
  labels:
    app: whokan-redis
    group: {{ .Values.app.group }}
spec:
  type: ClusterIP
  selector:
    app: whokan-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
